Output cli-download-multiple.gif

Set Shell zsh
Set FontSize 32
Set Width 2000
Set Height 600
Set Theme "Dracula"
Set TypingSpeed 75ms
Set Margin 20
Set MarginFill "#00b4d8"
Set BorderRadius 10
Set WindowBar Colorful
Set WindowBarSize 60

Hide
Env PROMPT '> '
Show


# Command
Type 'cat files.txt'

Sleep 1s

Enter 1

Sleep 2s

Ctrl+L

Type 'nsdf-cli download -f files.txt'

Sleep 1s

Enter 1

Sleep 10s

Type 'ls idx'

Sleep 1s

Enter

Sleep 5s
