site_name: NEXUS-DM Documentation
repo_url: https://github.com/nsdf-fabric/nsdf-slac
theme:
  name: material
  logo: assets/team/nsdflogo.png
  favicon: assets/team/nsdflogo.png
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.top
    - navigation.path
    - navigation.expand
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
nav:
  - Home: index.md
  - NSDF CLI Guide: cli.md
  - NSDF Library Guide: library.md
  - NSDF Dashboard Guide: dashboard.md
  - Contributing:
      - Contributing Guide: contributing.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - Acknowledgements: acknowledgment.md

extra_css:
  - stylesheets/overrides.css
copyright: >
  This research is supported by the National Science Foundation (NSF) awards #2138811, #2103845, #2334945, #2138296, and #2331152. The work presented here is partly obtained using resources from ACCESS TG-CIS210128. We thank the Scientist Cloud Storage.
