[project]
name = "nsdf-dark-matter-cli"
version = "0.1.0"
description = "NSDF Dark Matter CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3==1.35.99",
    "requests==2.32.3",
    "python-dotenv==1.0.1",
    "typer==0.15.1"
]
